# Generated by Django 5.2.3 on 2026-07-09 00:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessgoal",
            name="monto_objetivo",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
