export const PATHS = {
  login: "/login",
  app: "/",
  me: "/me",

  availability: "/availability",

  adminEspacios: "/admin/espacios",
  adminActividades: "/admin/actividades",
  adminEspacioActividad: "/admin/espacio-actividad",
  customers: "/admin/clientes",
  customerDetail: "/admin/clientes/:id",
  usersRoles: "/admin/usuarios-roles",
  inventory: "/admin/inventario",
  inventoryBatchHistory: "/admin/inventario/historial-lotes",
  inventoryPromotions: "/admin/inventario/promociones",
  businessGoalsDashboard: "/admin/metas-empresariales",
  businessGoalsList: "/admin/metas-empresariales/listado",
  businessGoalsPast: "/admin/metas-empresariales/pasadas",
  businessGoalCreate: "/admin/metas-empresariales/nueva",
  businessGoalVariables: "/admin/metas-empresariales/variables",
  businessGoalDetail: "/admin/metas-empresariales/:id",
  businessGoalEdit: "/admin/metas-empresariales/:id/editar",
  businessGoalNodes: "/admin/metas-empresariales/:id/nodos",
  businessGoalExpenses: "/admin/metas-empresariales/gastos-fijos",
  businessGoalHistory: "/admin/metas-empresariales/historial",
  audit: "/admin/auditoria",
  reservations: "/reservas",
  productSales: "/reservas/ventas-productos",
  salesHistory: "/reservas/historial-ventas",
  reservationHistory: "/historial-reservas",

  notFound: "*",
} as const;
