# Generated by Django 5.2.3 on 2025-12-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_create_admin"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cliente",
            new_name="users_clien_apellid_bd1a91_idx",
            old_name="users_clien_apellid_0e4c20_idx",
        ),
    ]
