# Generated by Django 5.2.3 on 2026-07-03 20:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


ALL_MODULES = [
    "availability",
    "reservations",
    "history",
    "customers",
    "spaces",
    "activities",
    "space_activities",
    "users",
]

STAFF_MODULES = [
    "availability",
    "reservations",
    "history",
    "customers",
    "spaces",
    "activities",
    "space_activities",
]

CLIENT_MODULES = ["availability", "reservations"]


def create_access_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserAccessProfile = apps.get_model("users", "UserAccessProfile")

    for user in User.objects.all():
        if user.is_superuser:
            role = "superuser"
            modules = ALL_MODULES
        elif user.is_staff:
            role = "admin"
            modules = STAFF_MODULES
        else:
            role = "cliente"
            modules = CLIENT_MODULES

        UserAccessProfile.objects.get_or_create(
            user=user,
            defaults={"role": role, "modules": modules},
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0003_rename_users_clien_apellid_0e4c20_idx_users_clien_apellid_bd1a91_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccessProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("role", models.CharField(default="operador", max_length=30)),
                ("modules", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_access_profile",
            },
        ),
        migrations.RunPython(create_access_profiles, migrations.RunPython.noop),
    ]
