# Generated by Django 5.2.3 on 2026-07-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_created_5a7975_idx",
            old_name="audit_log_created_0ffab1_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_user_id_3b54b4_idx",
            old_name="audit_log_user_id_096c0c_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_log_module_2b88a0_idx",
            old_name="audit_log_module_850e18_idx",
        ),
    ]
