# Generated by Django 5.2.3 on 2025-12-18 15:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "users",
            "0003_rename_users_clien_apellid_0e4c20_idx_users_clien_apellid_bd1a91_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Espacio",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("capacidad", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Disponible", "DISPONIBLE"),
                            ("Mantenimiento", "MANTENIMIENTO"),
                            ("Fuera de servicio", "FUERA_DE_SERVICIO"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=255)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="CSV: ej. techada,cesped,iluminación",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Espacio",
                "verbose_name_plural": "Espacios",
                "db_table": "espacios_espacio",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoActividad",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Actividad",
                "verbose_name_plural": "Tipos de Actividad",
                "db_table": "espacios_tipo_actividad",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Calendario",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("aforo_maximo", models.PositiveIntegerField()),
                ("titulo", models.CharField(max_length=150)),
                ("notas", models.TextField(blank=True)),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendarios",
                        to="espacios.espacio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendario de Espacio",
                "verbose_name_plural": "Calendarios de Espacio",
                "db_table": "espacios_calendario",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "descuento_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0 a 100",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                ("aplica_todos", models.BooleanField(default=False)),
                (
                    "espacios",
                    models.ManyToManyField(
                        blank=True, related_name="promociones", to="espacios.espacio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Promoción",
                "verbose_name_plural": "Promociones",
                "db_table": "espacios_promocion",
                "ordering": ["-fecha_inicio", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Regla",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diaria"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "intervalo",
                    models.PositiveIntegerField(
                        default=1, help_text="Cada cuántas unidades se repite (>=1)"
                    ),
                ),
                (
                    "weekday_mask",
                    models.CharField(
                        blank=True,
                        help_text='Sólo para WEEKLY: CSV con días, ej. "MO,WE,FR"',
                        max_length=50,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("fecha_desde", models.DateField(default=django.utils.timezone.now)),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas",
                        to="espacios.espacio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Disponibilidad",
                "verbose_name_plural": "Reglas de Disponibilidad",
                "db_table": "espacios_regla",
                "ordering": ["-fecha_desde", "espacio__nombre"],
            },
        ),
        migrations.CreateModel(
            name="ReglaGlobal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diaria"),
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensual"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "intervalo",
                    models.PositiveIntegerField(
                        default=1, help_text="Cada cuántas unidades se repite (>=1)"
                    ),
                ),
                (
                    "weekday_mask",
                    models.CharField(
                        blank=True,
                        help_text='Para WEEKLY: CSV ej. "MO,WE,FR". Para DAILY/MONTHLY se ignora.',
                        max_length=50,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("fecha_desde", models.DateField(default=django.utils.timezone.now)),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("aplica_todos", models.BooleanField(default=True)),
                (
                    "espacios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reglas_globales",
                        to="espacios.espacio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla Global de Disponibilidad",
                "verbose_name_plural": "Reglas Globales de Disponibilidad",
                "db_table": "espacios_regla_global",
                "ordering": ["-fecha_desde", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EspacioActividad",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("duracion_minutos", models.PositiveIntegerField(default=60)),
                (
                    "precio_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="espacio_actividades",
                        to="espacios.espacio",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="espacio_actividades",
                        to="espacios.tipoactividad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad por Espacio",
                "verbose_name_plural": "Actividades por Espacio",
                "db_table": "espacios_espacio_actividad",
                "ordering": ["espacio__nombre", "tipo__nombre"],
                "unique_together": {("espacio", "tipo")},
            },
        ),
        migrations.AddField(
            model_name="espacio",
            name="actividades",
            field=models.ManyToManyField(
                related_name="espacios",
                through="espacios.EspacioActividad",
                to="espacios.tipoactividad",
            ),
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RESERVADA", "Reservada"),
                            ("ACTIVA", "Activa"),
                            ("CANCELADA", "Cancelada"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="RESERVADA",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="users.cliente",
                    ),
                ),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="espacios.espacio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="espacios.tipoactividad",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["espacio", "inicio", "fin"],
                        name="espacios_re_espacio_e6d5d6_idx",
                    ),
                    models.Index(
                        fields=["cliente", "inicio"],
                        name="espacios_re_cliente_c44185_idx",
                    ),
                    models.Index(
                        fields=["estado"], name="espacios_re_estado_4164c8_idx"
                    ),
                ],
            },
        ),
    ]
