# Generated by Django 5.2.3 on 2025-12-18 19:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0001_initial"),
        (
            "users",
            "0003_rename_users_clien_apellid_0e4c20_idx_users_clien_apellid_bd1a91_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendario",
            options={"ordering": ["-fecha_inicio"]},
        ),
        migrations.AlterModelOptions(
            name="espacio",
            options={"ordering": ["nombre"]},
        ),
        migrations.AlterModelOptions(
            name="espacioactividad",
            options={},
        ),
        migrations.AlterModelOptions(
            name="promocion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="regla",
            options={},
        ),
        migrations.AlterModelOptions(
            name="reglaglobal",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tipoactividad",
            options={"ordering": ["nombre"]},
        ),
        migrations.RemoveIndex(
            model_name="reserva",
            name="espacios_re_estado_4164c8_idx",
        ),
        migrations.RemoveField(
            model_name="espacio",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="estado",
        ),
        migrations.AddField(
            model_name="espacio",
            name="estado_operativo",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "Disponible"),
                    ("MANTENIMIENTO", "Mantenimiento"),
                    ("FUERA_DE_SERVICIO", "Fuera de servicio"),
                ],
                default="DISPONIBLE",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="estado_reserva",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("ACTIVA", "Activa"),
                    ("FINALIZADA", "Finalizada"),
                    ("CANCELADA", "Cancelada"),
                    ("NO_SHOW", "No show"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="espacio",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="CSV: ej. techada,cesped,iluminacion",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="promocion",
            name="descuento_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="regla",
            name="intervalo",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="regla",
            name="weekday_mask",
            field=models.CharField(
                blank=True, help_text='Ej: "MO,WE,FR"', max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="reglaglobal",
            name="intervalo",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="reglaglobal",
            name="weekday_mask",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["estado_reserva"], name="espacios_re_estado__286cc2_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="reserva",
            table="espacios_reserva",
        ),
    ]
