# Generated by Django 5.2.3 on 2025-12-17 14:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RESERVADA", "Reservada"),
                            ("ACTIVA", "Activa"),
                            ("CANCELADA", "Cancelada"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="RESERVADA",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="espacios.tipoactividad",
                    ),
                ),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="espacios.espacio",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "db_table": "espacios_reserva",
                "ordering": ["-inicio"],
                "indexes": [
                    models.Index(
                        fields=["espacio", "inicio", "fin"],
                        name="espacios_re_espacio_e6d5d6_idx",
                    ),
                    models.Index(
                        fields=["usuario", "inicio"],
                        name="espacios_re_usuario_1fa982_idx",
                    ),
                    models.Index(
                        fields=["estado"], name="espacios_re_estado_4164c8_idx"
                    ),
                ],
            },
        ),
    ]
