# Generated by Django 5.2.3 on 2026-07-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0003_reserva_inventory_promotions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reservapromotioncredit",
            new_name="espacios_re_cliente_91829c_idx",
            old_name="espacios_re_cliente_11d9c3_idx",
        ),
    ]
